name = "companion-jobs"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "companion-jobs"
database_id = "2a789be5-eba3-4584-b59f-d8b0b99b4c4f"

[[r2_buckets]]
binding = "STORE"
bucket_name = "companion-store"

[[routes]]
pattern = "jobs-api.bchoor.com/*"
zone_id = "b10504faad00f03133ab37053799fe3f"

[observability.logs]
enabled = true
invocation_logs = true

[env.production]
vars = { ENVIRONMENT = "production" }
